### ISSUE TITLE
bin/detect - fail fast if buildpack.yml missing or not include go.import-path

### ISSUE THREAD

**Issue by drnic** [paketo-buildpacks/dep#8]
Currently, if you do not have a `buildpack.yml` or if its missing `go.import-path` then the `dep-cnb` fails:

```
===> BUILDING
[builder]
[builder] Go Compiler Buildpack v0.0.27
[builder]   Go 1.13: Contributing to layer
[builder]     Downloading from https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.linux-amd64-cflinuxfs3-8b3c3fb8.tar.gz
[builder]     Verifying checksum
[builder]     Expanding to /layers/org.cloudfoundry.go-compiler/go
[builder]
[builder] Dep Buildpack v0.0.26
[builder]     failure running build: no import-path found in buildpack.yml
[builder] Error: failed to build: exit status 102
```

But this is a slow failure - you've had to wait ages (depending on internet speed) for go1.13.linux-amd64-cflinuxfs3-8b3c3fb8.tar.gz to be downloaded first - to get an error that isn't obvious. So you fail a few more times before you read the various `integration/test-data/` apps to see what a `buildpack.yml` is supposed to look like.

Instead, could bin/detect fail or generate a warning ASAP if `buildpack.yml` is missing or misformed?

**Comment by thitch97** [comment]
After looking into this a bit, we are unsure if failing during detect is a pattern we would like to support. While we can add a warning in the short term, we plan to rewrite this CNB in the near future and cannot guarantee that the behavior would be supported long-term.

**Comment by ForestEckhardt** [comment]
Hey there @drnic,

After or restructure, the `import-path` field is now an optional field for the [`go-build`]() CNB. It would no longer make sense for us to look for this field during detection and fail. With this change I am going to close out this issue, but if you have any other issues or comments on this please feel free to reopen this issue to continue the discussion.
